import type { Metadata } from "next";
import { Geist } from "next/font/google";
import ClientThemeProvider from "@/components/ClientThemeProvider";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`} suppressHydrationWarning>
        <ClientThemeProvider>
          <main className="container mx-auto py-10">{children}</main>
          <footer className="flex gap-6 flex-wrap items-center justify-center">
            Footer
          </footer>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
